# Version: 1.0
# This file is the GitHub workflow to deploy the OpenDataApp service to Azure

name: Deploy ShinyR App

on:
  push:
    branches:
      - main

env:
  ACR_NAME: ${{ secrets.ACR_NAME }}
  AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
  AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: |
          az acr login --name ACR_NAME

      - name: Build and push Docker image
        run: |
          docker build -t ACR_NAME.azurecr.io/shinyr-app:${{ github.sha }} .
          docker push ACR_NAME.azurecr.io/shinyr-app:${{ github.sha }}

      - name: Deploy to Azure App Service
        run: |
          az webapp config container set --name $AZURE_WEBAPP_NAME --resource-group $AZURE_RESOURCE_GROUP --docker-custom-image-name $ACR_NAME.azurecr.io/shinyr-app:${{ github.sha }} --docker-registry-server-url https://$ACR_NAME.azurecr.io

